baseURL = 'https://xsfl.edu.kg/'
languageCode = 'zh-cn'
title = '我的相册网站'
theme = 'gallery'

copyright = "© Steve Wang"
defaultContentLanguage = "zh-cn"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
timeZone = "Asia/Shanghai"
timeout = "120s"

[params]
  defaultTheme = "dark"
  description = "使用Hugo Gallery主题创建的个人相册网站"
  title = "我的相册集"
  [params.author]
    email = "user@example.com"
    name = "Steve Wang"
  [params.socialIcons]
    github = "https://github.com/stevewang1/hugo-theme-gallery/"
    email = "mailto:user@example.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/stevewang1/hugo-theme-gallery/"
    weight = 3

[services]
  [services.rss]
    limit = 100
