name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.123.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.0'
          extended: true

      - name: Debug Information
        run: |
          echo "Hugo Version:"
          hugo version
          echo "Directory structure:"
          ls -la
          echo "Content directory:"
          ls -la content/ 2>/dev/null || echo "Content directory not found"
          echo "Themes directory:"
          ls -la themes/ 2>/dev/null || echo "Themes directory not found"

      - name: Build
        run: |
          hugo --minify --verbose --debug || {
            echo "Build failed, checking for common issues..."
            echo "Available themes:"
            ls -la themes/ 2>/dev/null || echo "No themes directory"
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4